[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
fuzz = { runs = 1_000 }
gas_reports = ["*"]
auto_detect_solc = false
bytecode_hash = "none"

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.1.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
