name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Boop The Snoot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge soldeer install

      - name: Run Forge build
        run: forge build
        id: build

      - name: Run Forge fmt
        run: forge fmt --check
        id: fmt

      - name: Run Forge tests
        run: forge test -vvv
        id: test
